In [87]:
import numpy as np
import pandas as pd
import random

Import data

In [88]:
train_data = pd.read_csv("h5w7_pr1_power_train.csv")
test_data = pd.read_csv("h5w7_pr1_power_test.csv")

In [89]:
train_data.insert(0, 'b', np.ones(train_data.shape[0]))
test_data.insert(0, 'b', np.ones(test_data.shape[0]))
X_train, y_train = train_data.iloc[:,:5].to_numpy(), train_data["PE"].to_numpy()
X_test, y_test = train_data.iloc[:,:5].to_numpy(), train_data["PE"].to_numpy()


In [90]:
X_train

array([[1.   , 0.405, 0.448, 0.984, 0.654],
       [1.   , 0.413, 0.523, 0.981, 0.727],
       [1.   , 0.673, 0.564, 0.98 , 0.439],
       ...,
       [1.   , 0.503, 0.553, 0.986, 0.668],
       [1.   , 0.419, 0.562, 0.992, 0.816],
       [1.   , 0.555, 0.623, 0.975, 0.767]])

Shuffle data

In [91]:
#Shuffle the trainning data
random.seed(4)
idx = np.arange(len(X_train))
random.shuffle(idx)
X_train = X_train[idx]
y_train = y_train[idx]

Tranform x to argument space

Initialization

In [152]:
def predict(w,x):
    return np.dot(w,x)

def eta(i,A,B):
    return A/(B+i)

In [116]:
epoch           = 100
N               = X_train.shape[0]
A               = [0.001, 0.1, 1, 10, 100]
B               = [1, 10, 100, 1000]
w_init          = np.random.uniform(-0.1, 0.1, 5)
J_init          = np.sum(np.power(predict(w_init,X_train.T) - y_train, 2))/N

In [164]:
error_rms       = np.zeros(epoch)
error_rms[0]    = np.power(J_init, 0.5)
error_rms[0]

454.2439838110133

In [171]:
w = w_init
J = J_init
for e in range(1,100):
    for n in range(N):
        i = (e-1)*N + n
        w = w - eta(i,10,100)*(predict(w,X_train[n])-y_train[n])*X_train[n]
        # print(w, "\n")
    J = np.sum(np.power(predict(w,X_train.T) - y_train, 2))/N
    error_rms[e] = np.power(J, 0.5)
    if(error_rms[e] < 0.001*error_rms[0]):
        print("halting condition 1 is met")
        break
    if(e == 99):
        print("halting condition 2 is met")
        break
error_rms

halting condition 2 is met


array([454.24398381,  25.11850661,  21.86239778,  20.47507937,
        19.63513197,  19.04214589,  18.5877028 ,  18.22163515,
        17.91669412,  17.65640252,  17.43003607,  17.2302367 ,
        17.05175017,  16.89070377,  16.74416776,  16.60987672,
        16.48604568,  16.37124515,  16.2643139 ,  16.16429667,
        16.07039876,  15.98195238,  15.89839136,  15.81923169,
        15.74405657,  15.67250464,  15.60426065,  15.53904803,
        15.47662289,  15.41676908,  15.3592942 ,  15.30402627,
        15.25081099,  15.19950937,  15.14999585,  15.10215658,
        15.05588807,  15.01109596,  14.96769397,  14.92560306,
        14.8847506 ,  14.84506972,  14.80649874,  14.76898062,
        14.73246254,  14.69689547,  14.66223383,  14.6284352 ,
        14.59546001,  14.56327127,  14.53183443,  14.50111709,
        14.47108886,  14.44172123,  14.41298736,  14.384862  ,
        14.35732133,  14.3303429 ,  14.30390549,  14.27798903,
        14.25257455,  14.22764406,  14.20318049,  14.17

In [155]:
error_rms

array([148.7884842 ,  51.46478363,  73.09023887, 146.48809959,
       109.34405316])

In [126]:
i = 5
w = w - eta(i)*(predict(w,X_train[i])-y_train[i])*X_train[i]
w

array([6413.77884407, 3947.39579977, 3952.35120678, 6329.08803404,
       4034.1766078 ])

In [123]:
w

array([-431.45884218,    2.14439933, -201.12286486, -429.49913647,
       -607.30416707])

In [109]:
np.sum(np.power(predict(w,X_train.T) - y_train, 2))/N

206445.27684079536

In [70]:
eta*(predict(w,X_train[1])-y_train[1])*X_train[1]

array([-471.01097038, -194.52753077, -246.33873751, -462.06176194,
       -342.42497546])

In [112]:
X_train

array([[1.   , 0.636, 0.736, 0.979, 0.643],
       [1.   , 0.493, 0.559, 0.985, 0.587],
       [1.   , 0.252, 0.514, 0.99 , 0.984],
       ...,
       [1.   , 0.179, 0.483, 0.98 , 0.752],
       [1.   , 0.447, 0.511, 0.986, 0.861],
       [1.   , 0.334, 0.49 , 0.978, 1.   ]])